; Auto-generated. Do not edit!


(cl:in-package pr2_common_action_msgs-msg)


;//! \htmlinclude TuckArmsFeedback.msg.html

(cl:defclass <TuckArmsFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TuckArmsFeedback (<TuckArmsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TuckArmsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TuckArmsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr2_common_action_msgs-msg:<TuckArmsFeedback> is deprecated: use pr2_common_action_msgs-msg:TuckArmsFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TuckArmsFeedback>) ostream)
  "Serializes a message object of type '<TuckArmsFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TuckArmsFeedback>) istream)
  "Deserializes a message object of type '<TuckArmsFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TuckArmsFeedback>)))
  "Returns string type for a message object of type '<TuckArmsFeedback>"
  "pr2_common_action_msgs/TuckArmsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TuckArmsFeedback)))
  "Returns string type for a message object of type 'TuckArmsFeedback"
  "pr2_common_action_msgs/TuckArmsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TuckArmsFeedback>)))
  "Returns md5sum for a message object of type '<TuckArmsFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TuckArmsFeedback)))
  "Returns md5sum for a message object of type 'TuckArmsFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TuckArmsFeedback>)))
  "Returns full string definition for message of type '<TuckArmsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TuckArmsFeedback)))
  "Returns full string definition for message of type 'TuckArmsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TuckArmsFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TuckArmsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TuckArmsFeedback
))
