(cl:in-package robot_controllers_msgs-msg)
(cl:export '(MAX_LINEAR_VELOCITY-VAL
          MAX_LINEAR_VELOCITY
          MAX_LINEAR_ACCELERATION-VAL
          MAX_LINEAR_ACCELERATION
          MAX_ANGULAR_VELOCITY-VAL
          MAX_ANGULAR_VELOCITY
          MAX_ANGULAR_ACCELERATION-VAL
          MAX_ANGULAR_ACCELERATION
          MAX_WHEEL_VELOCITY-VAL
          MAX_WHEEL_VELOCITY
          TRACK_WIDTH-VAL
          TRACK_WIDTH
          ANGULAR_VELOCITY_LIMITS_LINEAR_VELOCITY-VAL
          ANGULAR_VELOCITY_LIMITS_LINEAR_VELOCITY
          SCALE_TO_WHEEL_VELOCITY_LIMITS-VAL
          SCALE_TO_WHEEL_VELOCITY_LIMITS
))