; Auto-generated. Do not edit!


(cl:in-package robot_controllers_msgs-msg)


;//! \htmlinclude QueryControllerStatesGoal.msg.html

(cl:defclass <QueryControllerStatesGoal> (roslisp-msg-protocol:ros-message)
  ((updates
    :reader updates
    :initarg :updates
    :type (cl:vector robot_controllers_msgs-msg:ControllerState)
   :initform (cl:make-array 0 :element-type 'robot_controllers_msgs-msg:ControllerState :initial-element (cl:make-instance 'robot_controllers_msgs-msg:ControllerState))))
)

(cl:defclass QueryControllerStatesGoal (<QueryControllerStatesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <QueryControllerStatesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'QueryControllerStatesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_controllers_msgs-msg:<QueryControllerStatesGoal> is deprecated: use robot_controllers_msgs-msg:QueryControllerStatesGoal instead.")))

(cl:ensure-generic-function 'updates-val :lambda-list '(m))
(cl:defmethod updates-val ((m <QueryControllerStatesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_controllers_msgs-msg:updates-val is deprecated.  Use robot_controllers_msgs-msg:updates instead.")
  (updates m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <QueryControllerStatesGoal>) ostream)
  "Serializes a message object of type '<QueryControllerStatesGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'updates))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'updates))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <QueryControllerStatesGoal>) istream)
  "Deserializes a message object of type '<QueryControllerStatesGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'updates) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'updates)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'robot_controllers_msgs-msg:ControllerState))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<QueryControllerStatesGoal>)))
  "Returns string type for a message object of type '<QueryControllerStatesGoal>"
  "robot_controllers_msgs/QueryControllerStatesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'QueryControllerStatesGoal)))
  "Returns string type for a message object of type 'QueryControllerStatesGoal"
  "robot_controllers_msgs/QueryControllerStatesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<QueryControllerStatesGoal>)))
  "Returns md5sum for a message object of type '<QueryControllerStatesGoal>"
  "6ecbb837d1e8545d81a831a4c1c4bfcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'QueryControllerStatesGoal)))
  "Returns md5sum for a message object of type 'QueryControllerStatesGoal"
  "6ecbb837d1e8545d81a831a4c1c4bfcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<QueryControllerStatesGoal>)))
  "Returns full string definition for message of type '<QueryControllerStatesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This action allows one to query current information about~%# controller state, as well as change the controller state.~%~%# Action goal:~%# Requested changes to controller state. Each state must~%# have at least the controller name and new state. If the~%# controller type is non-empty, then it will be used to~%# make sure that the controller type matches. ~%ControllerState[] updates~%~%================================================================================~%MSG: robot_controllers_msgs/ControllerState~%# Valid states:~%~%uint8 STOPPED = 0~%uint8 RUNNING = 1~%uint8 ERROR = 2~%~%string name~%string type~%uint8 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'QueryControllerStatesGoal)))
  "Returns full string definition for message of type 'QueryControllerStatesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This action allows one to query current information about~%# controller state, as well as change the controller state.~%~%# Action goal:~%# Requested changes to controller state. Each state must~%# have at least the controller name and new state. If the~%# controller type is non-empty, then it will be used to~%# make sure that the controller type matches. ~%ControllerState[] updates~%~%================================================================================~%MSG: robot_controllers_msgs/ControllerState~%# Valid states:~%~%uint8 STOPPED = 0~%uint8 RUNNING = 1~%uint8 ERROR = 2~%~%string name~%string type~%uint8 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <QueryControllerStatesGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'updates) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <QueryControllerStatesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'QueryControllerStatesGoal
    (cl:cons ':updates (updates msg))
))
