; Auto-generated. Do not edit!


(cl:in-package robot_controllers_msgs-msg)


;//! \htmlinclude QueryControllerStatesFeedback.msg.html

(cl:defclass <QueryControllerStatesFeedback> (roslisp-msg-protocol:ros-message)
  ((state_diff
    :reader state_diff
    :initarg :state_diff
    :type (cl:vector robot_controllers_msgs-msg:ControllerState)
   :initform (cl:make-array 0 :element-type 'robot_controllers_msgs-msg:ControllerState :initial-element (cl:make-instance 'robot_controllers_msgs-msg:ControllerState))))
)

(cl:defclass QueryControllerStatesFeedback (<QueryControllerStatesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <QueryControllerStatesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'QueryControllerStatesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_controllers_msgs-msg:<QueryControllerStatesFeedback> is deprecated: use robot_controllers_msgs-msg:QueryControllerStatesFeedback instead.")))

(cl:ensure-generic-function 'state_diff-val :lambda-list '(m))
(cl:defmethod state_diff-val ((m <QueryControllerStatesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_controllers_msgs-msg:state_diff-val is deprecated.  Use robot_controllers_msgs-msg:state_diff instead.")
  (state_diff m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <QueryControllerStatesFeedback>) ostream)
  "Serializes a message object of type '<QueryControllerStatesFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'state_diff))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'state_diff))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <QueryControllerStatesFeedback>) istream)
  "Deserializes a message object of type '<QueryControllerStatesFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'state_diff) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'state_diff)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'robot_controllers_msgs-msg:ControllerState))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<QueryControllerStatesFeedback>)))
  "Returns string type for a message object of type '<QueryControllerStatesFeedback>"
  "robot_controllers_msgs/QueryControllerStatesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'QueryControllerStatesFeedback)))
  "Returns string type for a message object of type 'QueryControllerStatesFeedback"
  "robot_controllers_msgs/QueryControllerStatesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<QueryControllerStatesFeedback>)))
  "Returns md5sum for a message object of type '<QueryControllerStatesFeedback>"
  "884ebbcebb33b2855209539dadfa0dc6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'QueryControllerStatesFeedback)))
  "Returns md5sum for a message object of type 'QueryControllerStatesFeedback"
  "884ebbcebb33b2855209539dadfa0dc6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<QueryControllerStatesFeedback>)))
  "Returns full string definition for message of type '<QueryControllerStatesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Action feedback:~%# Status changes in controllers as they are started/stopped~%ControllerState[] state_diff~%~%~%================================================================================~%MSG: robot_controllers_msgs/ControllerState~%# Valid states:~%~%uint8 STOPPED = 0~%uint8 RUNNING = 1~%uint8 ERROR = 2~%~%string name~%string type~%uint8 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'QueryControllerStatesFeedback)))
  "Returns full string definition for message of type 'QueryControllerStatesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Action feedback:~%# Status changes in controllers as they are started/stopped~%ControllerState[] state_diff~%~%~%================================================================================~%MSG: robot_controllers_msgs/ControllerState~%# Valid states:~%~%uint8 STOPPED = 0~%uint8 RUNNING = 1~%uint8 ERROR = 2~%~%string name~%string type~%uint8 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <QueryControllerStatesFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'state_diff) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <QueryControllerStatesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'QueryControllerStatesFeedback
    (cl:cons ':state_diff (state_diff msg))
))
