// Generated by gencpp from file robot_controllers_msgs/QueryControllerStatesResult.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESRESULT_H
#define ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_controllers_msgs/ControllerState.h>

namespace robot_controllers_msgs
{
template <class ContainerAllocator>
struct QueryControllerStatesResult_
{
  typedef QueryControllerStatesResult_<ContainerAllocator> Type;

  QueryControllerStatesResult_()
    : state()  {
    }
  QueryControllerStatesResult_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> >::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> const> ConstPtr;

}; // struct QueryControllerStatesResult_

typedef ::robot_controllers_msgs::QueryControllerStatesResult_<std::allocator<void> > QueryControllerStatesResult;

typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesResult > QueryControllerStatesResultPtr;
typedef boost::shared_ptr< ::robot_controllers_msgs::QueryControllerStatesResult const> QueryControllerStatesResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_controllers_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_controllers_msgs': ['/home/kathleen/humanoid_robotics/project/fetch_ws/src/robot_controllers/robot_controllers_msgs/msg', '/home/kathleen/humanoid_robotics/project/fetch_ws/devel/.private/robot_controllers_msgs/share/robot_controllers_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95b3426d59527deffe501158443b26c9";
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95b3426d59527defULL;
  static const uint64_t static_value2 = 0xfe501158443b26c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_controllers_msgs/QueryControllerStatesResult";
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Action result:\n\
# The state of ALL controllers\n\
ControllerState[] state\n\
\n\
================================================================================\n\
MSG: robot_controllers_msgs/ControllerState\n\
# Valid states:\n\
\n\
uint8 STOPPED = 0\n\
uint8 RUNNING = 1\n\
uint8 ERROR = 2\n\
\n\
string name\n\
string type\n\
uint8 state\n\
";
  }

  static const char* value(const ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryControllerStatesResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_controllers_msgs::QueryControllerStatesResult_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_controllers_msgs::ControllerState_<ContainerAllocator> >::stream(s, indent + "    ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROLLERS_MSGS_MESSAGE_QUERYCONTROLLERSTATESRESULT_H
