// Generated by gencpp from file grasping_msgs/FindGraspableObjectsGoal.msg
// DO NOT EDIT!


#ifndef GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
#define GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasping_msgs
{
template <class ContainerAllocator>
struct FindGraspableObjectsGoal_
{
  typedef FindGraspableObjectsGoal_<ContainerAllocator> Type;

  FindGraspableObjectsGoal_()
    : plan_grasps(false)  {
    }
  FindGraspableObjectsGoal_(const ContainerAllocator& _alloc)
    : plan_grasps(false)  {
  (void)_alloc;
    }



   typedef uint8_t _plan_grasps_type;
  _plan_grasps_type plan_grasps;





  typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FindGraspableObjectsGoal_

typedef ::grasping_msgs::FindGraspableObjectsGoal_<std::allocator<void> > FindGraspableObjectsGoal;

typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal > FindGraspableObjectsGoalPtr;
typedef boost::shared_ptr< ::grasping_msgs::FindGraspableObjectsGoal const> FindGraspableObjectsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace grasping_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'grasping_msgs': ['/home/kathleen/humanoid_robotics/project/fetch_ws/devel/.private/grasping_msgs/share/grasping_msgs/msg', '/home/kathleen/humanoid_robotics/project/fetch_ws/src/grasping_msgs/msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aadd364d1b04bf1e9e9fdbdce5637d4";
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aadd364d1b04bf1ULL;
  static const uint64_t static_value2 = 0xe9e9fdbdce5637d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasping_msgs/FindGraspableObjectsGoal";
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
###########################################################\n\
# This action is called for integrated object detection and\n\
#  grasp planning, such as in base_grasping_perception\n\
\n\
# Set to false to disable grasp planning, returning only the objects found\n\
bool plan_grasps\n\
";
  }

  static const char* value(const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_grasps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindGraspableObjectsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasping_msgs::FindGraspableObjectsGoal_<ContainerAllocator>& v)
  {
    s << indent << "plan_grasps: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_grasps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPING_MSGS_MESSAGE_FINDGRASPABLEOBJECTSGOAL_H
