; Auto-generated. Do not edit!


(cl:in-package grasping_msgs-msg)


;//! \htmlinclude FindGraspableObjectsActionGoal.msg.html

(cl:defclass <FindGraspableObjectsActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type grasping_msgs-msg:FindGraspableObjectsGoal
    :initform (cl:make-instance 'grasping_msgs-msg:FindGraspableObjectsGoal)))
)

(cl:defclass FindGraspableObjectsActionGoal (<FindGraspableObjectsActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindGraspableObjectsActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindGraspableObjectsActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grasping_msgs-msg:<FindGraspableObjectsActionGoal> is deprecated: use grasping_msgs-msg:FindGraspableObjectsActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <FindGraspableObjectsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasping_msgs-msg:header-val is deprecated.  Use grasping_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <FindGraspableObjectsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasping_msgs-msg:goal_id-val is deprecated.  Use grasping_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <FindGraspableObjectsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasping_msgs-msg:goal-val is deprecated.  Use grasping_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindGraspableObjectsActionGoal>) ostream)
  "Serializes a message object of type '<FindGraspableObjectsActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindGraspableObjectsActionGoal>) istream)
  "Deserializes a message object of type '<FindGraspableObjectsActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindGraspableObjectsActionGoal>)))
  "Returns string type for a message object of type '<FindGraspableObjectsActionGoal>"
  "grasping_msgs/FindGraspableObjectsActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindGraspableObjectsActionGoal)))
  "Returns string type for a message object of type 'FindGraspableObjectsActionGoal"
  "grasping_msgs/FindGraspableObjectsActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindGraspableObjectsActionGoal>)))
  "Returns md5sum for a message object of type '<FindGraspableObjectsActionGoal>"
  "8308965ee8ae423cd6ede0a494bc6f1e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindGraspableObjectsActionGoal)))
  "Returns md5sum for a message object of type 'FindGraspableObjectsActionGoal"
  "8308965ee8ae423cd6ede0a494bc6f1e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindGraspableObjectsActionGoal>)))
  "Returns full string definition for message of type '<FindGraspableObjectsActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FindGraspableObjectsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: grasping_msgs/FindGraspableObjectsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###########################################################~%# This action is called for integrated object detection and~%#  grasp planning, such as in base_grasping_perception~%~%# Set to false to disable grasp planning, returning only the objects found~%bool plan_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindGraspableObjectsActionGoal)))
  "Returns full string definition for message of type 'FindGraspableObjectsActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%FindGraspableObjectsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: grasping_msgs/FindGraspableObjectsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###########################################################~%# This action is called for integrated object detection and~%#  grasp planning, such as in base_grasping_perception~%~%# Set to false to disable grasp planning, returning only the objects found~%bool plan_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindGraspableObjectsActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindGraspableObjectsActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FindGraspableObjectsActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
