; Auto-generated. Do not edit!


(cl:in-package grasping_msgs-msg)


;//! \htmlinclude FindGraspableObjectsGoal.msg.html

(cl:defclass <FindGraspableObjectsGoal> (roslisp-msg-protocol:ros-message)
  ((plan_grasps
    :reader plan_grasps
    :initarg :plan_grasps
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FindGraspableObjectsGoal (<FindGraspableObjectsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FindGraspableObjectsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FindGraspableObjectsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grasping_msgs-msg:<FindGraspableObjectsGoal> is deprecated: use grasping_msgs-msg:FindGraspableObjectsGoal instead.")))

(cl:ensure-generic-function 'plan_grasps-val :lambda-list '(m))
(cl:defmethod plan_grasps-val ((m <FindGraspableObjectsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grasping_msgs-msg:plan_grasps-val is deprecated.  Use grasping_msgs-msg:plan_grasps instead.")
  (plan_grasps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FindGraspableObjectsGoal>) ostream)
  "Serializes a message object of type '<FindGraspableObjectsGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'plan_grasps) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FindGraspableObjectsGoal>) istream)
  "Deserializes a message object of type '<FindGraspableObjectsGoal>"
    (cl:setf (cl:slot-value msg 'plan_grasps) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FindGraspableObjectsGoal>)))
  "Returns string type for a message object of type '<FindGraspableObjectsGoal>"
  "grasping_msgs/FindGraspableObjectsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FindGraspableObjectsGoal)))
  "Returns string type for a message object of type 'FindGraspableObjectsGoal"
  "grasping_msgs/FindGraspableObjectsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FindGraspableObjectsGoal>)))
  "Returns md5sum for a message object of type '<FindGraspableObjectsGoal>"
  "4aadd364d1b04bf1e9e9fdbdce5637d4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FindGraspableObjectsGoal)))
  "Returns md5sum for a message object of type 'FindGraspableObjectsGoal"
  "4aadd364d1b04bf1e9e9fdbdce5637d4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FindGraspableObjectsGoal>)))
  "Returns full string definition for message of type '<FindGraspableObjectsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###########################################################~%# This action is called for integrated object detection and~%#  grasp planning, such as in base_grasping_perception~%~%# Set to false to disable grasp planning, returning only the objects found~%bool plan_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FindGraspableObjectsGoal)))
  "Returns full string definition for message of type 'FindGraspableObjectsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###########################################################~%# This action is called for integrated object detection and~%#  grasp planning, such as in base_grasping_perception~%~%# Set to false to disable grasp planning, returning only the objects found~%bool plan_grasps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FindGraspableObjectsGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FindGraspableObjectsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FindGraspableObjectsGoal
    (cl:cons ':plan_grasps (plan_grasps msg))
))
