(cl:in-package pr2_mechanism_controllers-msg)
(cl:export '(COMMAND-VAL
          COMMAND
          JOINT_COMMAND-VAL
          JOINT_COMMAND
          JOINT_ERROR-VAL
          JOINT_ERROR
          JOINT_VELOCITY_COMMANDED-VAL
          JOINT_VELOCITY_COMMANDED
          JOINT_VELOCITY_MEASURED-VAL
          JOINT_VELOCITY_MEASURED
          JOINT_EFFORT_MEASURED-VAL
          JOINT_EFFORT_MEASURED
          JOINT_EFFORT_COMMANDED-VAL
          JOINT_EFFORT_COMMANDED
          JOINT_EFFORT_ERROR-VAL
          JOINT_EFFORT_ERROR
          JOINT_NAMES-VAL
          JOINT_NAMES
))