(cl:defpackage ethercat_trigger_controllers-srv
  (:use )
  (:export
   "SETMULTIWAVEFORM"
   "<SETMULTIWAVEFORM-REQUEST>"
   "SETMULTIWAVEFORM-REQUEST"
   "<SETMULTIWAVEFORM-RESPONSE>"
   "SETMULTIWAVEFORM-RESPONSE"
   "SETWAVEFORM"
   "<SETWAVEFORM-REQUEST>"
   "SETWAVEFORM-REQUEST"
   "<SETWAVEFORM-RESPONSE>"
   "SETWAVEFORM-RESPONSE"
  ))

