// Auto-generated. Do not edit!

// (in-package pr2_tilt_laser_interface.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GetSnapshotGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.start_angle = null;
      this.end_angle = null;
      this.speed = null;
      this.hi_fidelity = null;
      this.continuous = null;
    }
    else {
      if (initObj.hasOwnProperty('start_angle')) {
        this.start_angle = initObj.start_angle
      }
      else {
        this.start_angle = 0.0;
      }
      if (initObj.hasOwnProperty('end_angle')) {
        this.end_angle = initObj.end_angle
      }
      else {
        this.end_angle = 0.0;
      }
      if (initObj.hasOwnProperty('speed')) {
        this.speed = initObj.speed
      }
      else {
        this.speed = 0.0;
      }
      if (initObj.hasOwnProperty('hi_fidelity')) {
        this.hi_fidelity = initObj.hi_fidelity
      }
      else {
        this.hi_fidelity = false;
      }
      if (initObj.hasOwnProperty('continuous')) {
        this.continuous = initObj.continuous
      }
      else {
        this.continuous = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GetSnapshotGoal
    // Serialize message field [start_angle]
    bufferOffset = _serializer.float32(obj.start_angle, buffer, bufferOffset);
    // Serialize message field [end_angle]
    bufferOffset = _serializer.float32(obj.end_angle, buffer, bufferOffset);
    // Serialize message field [speed]
    bufferOffset = _serializer.float32(obj.speed, buffer, bufferOffset);
    // Serialize message field [hi_fidelity]
    bufferOffset = _serializer.bool(obj.hi_fidelity, buffer, bufferOffset);
    // Serialize message field [continuous]
    bufferOffset = _serializer.bool(obj.continuous, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GetSnapshotGoal
    let len;
    let data = new GetSnapshotGoal(null);
    // Deserialize message field [start_angle]
    data.start_angle = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [end_angle]
    data.end_angle = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [speed]
    data.speed = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [hi_fidelity]
    data.hi_fidelity = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [continuous]
    data.continuous = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 14;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pr2_tilt_laser_interface/GetSnapshotGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '464673531a0e6172d0d965e354c952f0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    # We always want to command. Don't need this bool
    # bool command_laser   # True: Use the command below. False: Use existing profile
    float32 start_angle
    float32 end_angle
    float32 speed
    bool hi_fidelity
    bool continuous
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GetSnapshotGoal(null);
    if (msg.start_angle !== undefined) {
      resolved.start_angle = msg.start_angle;
    }
    else {
      resolved.start_angle = 0.0
    }

    if (msg.end_angle !== undefined) {
      resolved.end_angle = msg.end_angle;
    }
    else {
      resolved.end_angle = 0.0
    }

    if (msg.speed !== undefined) {
      resolved.speed = msg.speed;
    }
    else {
      resolved.speed = 0.0
    }

    if (msg.hi_fidelity !== undefined) {
      resolved.hi_fidelity = msg.hi_fidelity;
    }
    else {
      resolved.hi_fidelity = false
    }

    if (msg.continuous !== undefined) {
      resolved.continuous = msg.continuous;
    }
    else {
      resolved.continuous = false
    }

    return resolved;
    }
};

module.exports = GetSnapshotGoal;
