(cl:defpackage pr2_tilt_laser_interface-msg
  (:use )
  (:export
   "<GETSNAPSHOTACTION>"
   "GETSNAPSHOTACTION"
   "<GETSNAPSHOTACTIONFEEDBACK>"
   "GETSNAPSHOTACTIONFEEDBACK"
   "<GETSNAPSHOTACTIONGOAL>"
   "GETSNAPSHOTACTIONGOAL"
   "<GETSNAPSHOTACTIONRESULT>"
   "GETSNAPSHOTACTIONRESULT"
   "<GETSNAPSHOTFEEDBACK>"
   "GETSNAPSHOTFEEDBACK"
   "<GETSNAPSHOTGOAL>"
   "GETSNAPSHOTGOAL"
   "<GETSNAPSHOTRESULT>"
   "GETSNAPSHOTRESULT"
  ))

