// Auto-generated. Do not edit!

// (in-package pr2_common_action_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TuckArmsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.tuck_left = null;
      this.tuck_right = null;
    }
    else {
      if (initObj.hasOwnProperty('tuck_left')) {
        this.tuck_left = initObj.tuck_left
      }
      else {
        this.tuck_left = false;
      }
      if (initObj.hasOwnProperty('tuck_right')) {
        this.tuck_right = initObj.tuck_right
      }
      else {
        this.tuck_right = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TuckArmsResult
    // Serialize message field [tuck_left]
    bufferOffset = _serializer.bool(obj.tuck_left, buffer, bufferOffset);
    // Serialize message field [tuck_right]
    bufferOffset = _serializer.bool(obj.tuck_right, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TuckArmsResult
    let len;
    let data = new TuckArmsResult(null);
    // Deserialize message field [tuck_left]
    data.tuck_left = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [tuck_right]
    data.tuck_right = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pr2_common_action_msgs/TuckArmsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a07b11078a50f9881dc3004ca1174834';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    bool tuck_left
    bool tuck_right
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TuckArmsResult(null);
    if (msg.tuck_left !== undefined) {
      resolved.tuck_left = msg.tuck_left;
    }
    else {
      resolved.tuck_left = false
    }

    if (msg.tuck_right !== undefined) {
      resolved.tuck_right = msg.tuck_right;
    }
    else {
      resolved.tuck_right = false
    }

    return resolved;
    }
};

module.exports = TuckArmsResult;
