#!/bin/sh
final="$@"

# add ros plugin if does not exist
if [ `expr "$final" : '.*libgazebo_ros_paths_plugin\.so.*'` -eq 0 ]
then
  final="$final -s `rospack find gazebo`/lib/libgazebo_ros_paths_plugin.so"
fi

if [ `expr "$final" : '.*libgazebo\_ros\_api\_plugin\.so.*'` -eq 0 ]
then
  final="$final -s `rospack find gazebo`/lib/libgazebo_ros_api_plugin.so"
fi

. `rospack find gazebo`/scripts/setup.sh && `rospack find gazebo`/gazebo/bin/gzserver $final
