#!/bin/sh
final="$@"

# add ros plugin if does not exist
if [ `expr "$final" : '.*libgazebo_ros_paths_plugin\.so.*'` -eq 0 ]
then
  final="$final -g `rospack find gazebo`/lib/libgazebo_ros_paths_plugin.so"
fi

. `rospack find gazebo`/scripts/setup.sh && `rospack find gazebo`/gazebo/bin/gzclient $final
